[package]
name = "rmp-futures"
version = "0.1.0"
authors = ["Tyler Hall <tylerwhall@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3"
rmp = "0.8"
rmpv = "0.4"
futures-preview = "0.3.0-alpha.17"

[profile.release]
lto = true
debug = true
